Added client libraries for Ground
ground-context/ground pull request #112
Opened 2017-08-15 17:33 UTC by andreaskari

Created client libraries in Python and Java for Ground

2017-08-16 20:46 UTC, vsreekanti requested changes
A few other points: 

* Why is `gradle-wrapper.jar` being committed? 
* Let's turn off the contact information field in the autogenerated code. Doesn't make sense to put an email there when we want people to engage via Github.
* If we're not going to have tests, let's remove that frm the skeleton as well.

2017-08-16 20:46 UTC, vsreekanti commented on client/java/.gitignore
> +*.class
Please remove nested `.gitignore`s. If there's something that needs to be ignore, it should be in the toplevel `.gitignore`.

2017-08-16 20:46 UTC, vsreekanti commented on build.sbt
> +name := """ground"""
Whitespace.

2017-08-16 20:46 UTC, vsreekanti commented on client/java/.swagger-codegen-ignore
> +# Swagger Codegen Ignore
This seems to be empty? If unnecessary, please remove.

2017-08-16 20:46 UTC, vsreekanti commented on client/java/.travis.yml
> +#
There's no need for a special `.travis.yml` for each client. The necessary logic here should be merged into the top level `.travis.yml`.

2017-08-16 20:46 UTC, vsreekanti commented on client/java/README.md
> +    <artifactId>swagger-java-client</artifactId>
Shouldn't this reflect the actual project and be `edu.berkeley.ground.ground-java-client`? We wouldn't be able to publish this to Maven central under `io.swagger`, and the examples below seem like dummy examples.

2017-08-16 20:46 UTC, vsreekanti commented on client/java/README.md
> +## Documentation for Models
Remove unnecessary headings.

2017-08-16 20:46 UTC, vsreekanti commented on client/java/build.gradle
> +            sourceCompatibility JavaVersion.VERSION_1_7
Ground uses Java 8. The client should also.

2017-08-16 20:46 UTC, vsreekanti commented on client/java/build.sbt
> +lazy val root = (project in file(".")).
Why is there both a `build.sbt` and a `build.gradle` in the Java client?

2017-08-16 20:46 UTC, vsreekanti commented on client/java/git_push.sh
> +#!/bin/sh
Why do we need this file?

2017-08-16 20:46 UTC, vsreekanti commented on client/java/settings.gradle
> +rootProject.name = "swagger-java-client"
Again, we should have a non-generic project name. Same with the `pom.xml` above.

2017-08-16 20:46 UTC, vsreekanti commented on client/java/src/main/java/io/swagger/client/ApiCallback.java
> +/*
It seems like everything has been generated with the generic template. Things should be in the `edu.berkeley.ground.client` package.

2017-08-16 20:46 UTC, vsreekanti commented on client/python/.gitignore
> +# Byte-compiled / optimized / DLL files
Same comments for the Python skeleton.

2017-08-16 20:46 UTC, vsreekanti commented on client/python/docs/DefaultApi.md
> +# swagger_client.DefaultApi
Can we avoid duplication of this? Seems like the same as the Java version.

2017-08-16 20:46 UTC, vsreekanti commented on client/python/setup.py
> +NAME = "swagger-client"
Same comment about naming.

2017-08-16 23:15 UTC, andreaskari commented
The latest commit on "master" and "client" branches have the latest and greatest clients. I did a major cleanup. Let me know what else must be done.

2017-08-18 21:25 UTC, vsreekanti commented
Looks much better, thanks! Unfortunately, tests aren't passing. You should be able to look more closely [here](https://travis-ci.org/ground-context/ground/builds/265373431?utm_source=github_status&utm_medium=notification).

One nit: I'm still not sure why we have multiple build files (Maven, SBT, Gradle) in the Java project.

Once the tests pass, we should be good to go with this!

2017-08-25 07:17 UTC, andreaskari commented
All the tests are now passing and everything should be good to go

2017-08-25 17:04 UTC, vsreekanti commented
I might have missed something, @andreaskari, but it seems like the reason the tests are passing is because we aren't actually testing the client libraries. When I said earlier I wanted the tests to pass, I meant that we should be testing the client libraries like you were earlier, but we should modify the environment so that the client library tests are passing in addition to the server-side tests. Let me know if you need any help with this.

Also, there have been some changes to the master branch since you opened the PR, so please merge the latest changes into your branch.

2017-09-05 18:10 UTC, vsreekanti approved these changes

2017-09-05 18:11 UTC, merged