[GROUND-24] Refactor Hive Plugin and migrate to the Ground REST API
ground-context/ground pull request #41
Opened 2017-02-21 01:08 UTC by ramach

Ground Hive Plugin version using Ground REST APIs. Test cases are not working (see below) - am still debugging. It is NOT ready for merge yet - since there are major changes am submitting  to get the process started

Error during node creation:

127.0.0.1 - - [21/Feb/2017:00:28:40 +0000] "POST /nodes/_METASTORE HTTP/1.1" 500 110 "-" "Jakarta Commons-HttpClient/3.1" 36
INFO  [2017-02-21 00:28:40,986] edu.berkeley.ground.resources.NodesResource: Retrieving the latest version of node _METASTORE.
ERROR [2017-02-21 00:28:41,008] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: b3b8195962d955a9
! org.neo4j.driver.v1.exceptions.ClientException: The client has provided incorrect authentication details too many times in a row.

2017-02-21 19:06 UTC, vsreekanti requested changes
A couple general notes:
1. We should definitely switch to the new API because it affects how you create versions and their IDs and so on.
2. Please use `this` before instance variables just as a matter of practice.
3. I think we might want to discuss the APIs a little more. We definitely don't need to be creating new `StructureVersion`s every time a new `NodeVersion` is created for example, so I think there might be some misunderstandings there.

2017-02-21 19:06 UTC, vsreekanti commented on plugins/hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundDatabase.java
> +            Edge edge = this.getEdge(nodeVersion);
Why does `getEdge` take a `nodeVersion`?

2017-02-21 19:06 UTC, vsreekanti commented on plugins/hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundDatabase.java
> +            throw new GroundException(e);
We shouldn't use `GroundException` for this stuff. I created that for internal use; is there a default Hive Metastore exception? If not, we could create another one for this implementation.

2017-02-21 19:06 UTC, vsreekanti commented on plugins/hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundDatabase.java
> +            structVersionAttribs.put(dbName, GroundType.STRING);
Why is `dbName` being used as the key for the tag? Shouldn't the required key be "dbName" and not the actual name of the database?

2017-02-21 19:06 UTC, vsreekanti commented on plugins/hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundDatabase.java
> +            Tag dbTag = new Tag("1.0.0", dbName, JsonUtil.toJSON(db), GroundType.STRING);
With the new API, the versionId is a long, not a String.

2017-02-21 19:06 UTC, vsreekanti commented on plugins/hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundDatabase.java
> +            NodeVersion dbNodeVersion = this.createDatabase(prevDb);
Why are we creating new database `NodeVersion` when we create a new table?

2017-02-21 19:06 UTC, vsreekanti commented on plugins/hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundDatabase.java
> +            StructureVersion sv = groundReadWrite.createStructureVersion(structure.getName(), structure.getId(),
And why are we creating a new `StructureVersion`? Unless the attributes required by a `StructureVersion` are changing, I don't see any reason to create a new one.

2017-02-21 19:06 UTC, vsreekanti commented on plugins/hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundDatabase.java
> +                String tableNodeId = "Nodes." + tableName;
1. In general, this stuff shouldn't be hardcoded.
2. In the new ID API, these aren't deterministic strings but are longs instead, so you should try to cache or bug me to change APIs that are inhospitable to easy retrieval. :-)

2017-02-21 19:06 UTC, vsreekanti commented on plugins/hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundDatabase.java
> +                        StructureVersion sv = groundReadWrite.createStructureVersion(structure.getName(), structure.getId(),
Same thing about unnecessary recreation of `StructureVersion`s.

2017-02-21 19:06 UTC, vsreekanti commented on plugins/hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundMetaStore.java
> +    String edgeId = nodeVersion.getNodeId();
Why is the `edgeId` the id of the `nodeVersion`?

2017-02-21 19:06 UTC, vsreekanti commented on plugins/hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundReadWrite.java
> - */
Please put the license back at the top of the file.

2017-02-21 19:06 UTC, vsreekanti commented on plugins/hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundReadWrite.java
> +                                                        // from resources
Comment formatting is off.

2017-02-21 19:06 UTC, vsreekanti commented on plugins/hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundReadWrite.java
> +        Node node = new Node("id", name);
This is unnecessary for creating a new `Node`. In fact, it's going to be incorrect because the `id` field will be set by the server and returned to you in the response to the POST.

2017-02-21 19:06 UTC, vsreekanti commented on plugins/hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundReadWrite.java
> +        // TODO Auto-generated method stub
It doesn't seem like this is autogenerated?

2017-02-21 19:06 UTC, vsreekanti commented on plugins/hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundReadWrite.java
> +        Edge node = new Edge("id", name);
Same idea here as `Node` creation above.

2017-02-21 19:56 UTC, ramach commented on plugins/hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundReadWrite.java
> +        Edge node = new Edge("id", name);
Thanks! will fix. Most of these were inherited from old code - will clean and revise

2017-02-25 23:42 UTC, ramach commented on plugins/hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundReadWrite.java
> +        Node node = new Node("id", name);
removed

2017-02-25 23:42 UTC, ramach commented on plugins/hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundReadWrite.java
> +        // TODO Auto-generated method stub
fixed

2017-02-25 23:42 UTC, ramach commented on plugins/hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundReadWrite.java
> +        Edge node = new Edge("id", name);
removed

2017-02-25 23:42 UTC, ramach commented on plugins/hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundReadWrite.java
> - */
yes

2017-02-25 23:43 UTC, ramach commented on plugins/hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundReadWrite.java
> +                                                        // from resources
fixed

2017-02-25 23:44 UTC, ramach commented on plugins/hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundDatabase.java
> +            throw new GroundException(e);
Yes. Use MetaStoreException - fixed

2017-02-26 01:03 UTC, ramach commented on plugins/hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundDatabase.java
> +            throw new GroundException(e);
For internal (private) methods it is ok to throw GroundException. Only for public APIs MetaException is required

2017-02-26 01:21 UTC, ramach commented on plugins/hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundDatabase.java
> +            throw new GroundException(e);
Again for RawStore implementation we make sure to use only MetastoreException. For internal methods we use GroundException

2017-02-26 01:46 UTC, ramach commented on plugins/hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundDatabase.java
> +            structVersionAttribs.put(dbName, GroundType.STRING);
not clear - can you clarify

2017-02-26 03:06 UTC, vsreekanti commented on plugins/hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundDatabase.java
> +            structVersionAttribs.put(dbName, GroundType.STRING);
You're creating a structure version here. A structure is meant to be like a struct in C where you specify a set of fields that are enforced when you create a node version with that structure version. You're creating a structure where one of the required fields is whatever is stored in the `dbName` variable. e.g., if the string "Ground" was the name of the database, then you would require a Tag with key "Ground". Based on my understanding, it seemed like we would want the key to actually be "dbName" and the value to be "Ground".

2017-02-26 17:22 UTC, ramach commented on plugins/hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundDatabase.java
> +            structVersionAttribs.put(dbName, GroundType.STRING);
got it thanks! Essentially have a generic key (like datebaseName, tableName, partitionName) and values will be a list - of a particular key type - correct?

2017-02-26 19:15 UTC, ramach commented on plugins/hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundDatabase.java
> +            structVersionAttribs.put(dbName, GroundType.STRING);
let me expand. The correct sequence will be while creating a new database, 
first check if the structure for database exists
if (getStructure("database") == null) //key here is "database" not database actual name
   dbStructure = createStructure("databaee")
   structureVersion sv = createStructureVersion(GUID, dbStructure.getId(), attrinutes)
else {
   structureVersion = getStructureVersion(dbStructure.getId); //very important get structureVersion using structure ID and NOT GUID
}
now create a tag with actual dbName 
tag = createTag(GUID, databaseName, ..._)
createNodeVersion(GUID, tag, sv.getId(), .....)

is this the correct? Similar flow for tables, partitions....
this way we will create only handful structure versions

2017-02-26 19:19 UTC, ramach commented on plugins/hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundDatabase.java
> +            Tag dbTag = new Tag("1.0.0", dbName, JsonUtil.toJSON(db), GroundType.STRING);
I pulled upstream master in to fork and changed these to long - how are we going to generate these uniqueIds - just a sequence of versions?

2017-02-26 22:57 UTC, ramach commented on plugins/hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundDatabase.java
> +            NodeVersion dbNodeVersion = this.createDatabase(prevDb);
there are 2 possibilities
1) create a new table in an existing database
2) move or rename a table to a different database
alter table table_a rename to new_database.table_a
if the nodeversion for the new database does not exist we need to create both

2017-03-03 22:41 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2017-03-03 22:50 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2017-03-06 06:13 UTC, ramach commented
am closing this pull request and will open a new one soon

2017-03-06 06:13 UTC, closed without merging

2017-03-06 06:14 UTC, ramach commented
I am closing this pull request and will open a new one with revisions based on review