Update CI
ground-context/ground pull request #48
Opened 2017-03-03 22:41 UTC by vsreekanti

2017-03-03 22:46 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-03-03 22:46 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ground-PRB/1/
Test FAILed.

2017-03-03 22:48 UTC, vsreekanti commented
Test this please.

2017-03-03 22:53 UTC, vsreekanti commented
Test this please.

2017-03-03 22:56 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-03-03 22:56 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ground-PRB/2/
Test FAILed.

2017-03-03 22:58 UTC, shaneknapp commented
test this please

2017-03-07 00:03 UTC, shaneknapp requested changes
i've been testing on our staging worker, and got the docker container build working w/these changes.  your tests are failing, but that could just be from an old commit.

2017-03-07 00:03 UTC, shaneknapp commented on ci/Dockerfile
> +ADD ground/ /tmp/ground
change this to:
ADD ./ /tmp/ground

2017-03-07 00:03 UTC, shaneknapp commented on ci/Dockerfile
> +ADD ground/ci/start_servers_and_test.sh /tmp/
change this to:
ADD ./ci/start_servers_and_test.sh /tmp/

2017-03-07 00:18 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-03-07 00:18 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ground-PRB/3/
Test FAILed.

2017-03-07 00:26 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-03-07 00:26 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ground-PRB/4/
Test FAILed.

2017-03-07 00:31 UTC, shaneknapp commented on ci/start_servers_and_test.sh
> +if [ -z "$MASTER_BUILD" ]
change to:
if [ ! -z "${MASTER_BUILD}" ]

2017-03-07 00:40 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-03-07 00:40 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ground-PRB/5/
Test PASSed.

2017-03-07 00:44 UTC, merged