[GROUND-26] db: Cache prepared statements
ground-context/ground pull request #51
Opened 2017-03-07 02:57 UTC by mc10

This PR is broken up into two commits: one part with just a file-level reformat, and the other with the real changes. I'm not quite happy with how connections are being closed at the moment; I'm hoping to use [try-with-resources](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) to properly clean them up.

2017-03-07 03:00 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2017-03-07 03:01 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2017-03-08 02:31 UTC, shaneknapp commented
ok to test

2017-03-08 02:37 UTC, AmplabJenkins commented
Build finished. Test FAILed.

2017-03-08 02:37 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ground-PRB/7/
Test FAILed.

2017-03-08 10:04 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-03-08 10:04 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ground-PRB/8/
Test FAILed.

2017-03-08 10:05 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-03-08 10:05 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ground-PRB/9/
Test FAILed.

2017-03-08 10:16 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-03-08 10:16 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ground-PRB/10/
Test PASSed.

2017-03-12 01:09 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-03-12 01:09 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ground-PRB/11/
Test FAILed.

2017-03-12 01:15 UTC, vsreekanti commented
Haven't looked at the code yet. I'll take a look on Tuesday.

From the CI test output, it looks like a lot (all?) of the Cassandra tests are failing.

2017-03-12 01:19 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-03-12 01:19 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ground-PRB/12/
Test FAILed.

2017-03-12 10:16 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-03-12 10:16 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ground-PRB/13/
Test PASSed.

2017-03-13 02:21 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2017-03-13 02:21 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ground-PRB/14/
Test PASSed.

2017-03-15 18:40 UTC, vsreekanti requested changes
Things look great for the most part. The only thing I'm not sure about is the use of the DB exception in the factory APIs. Is there any particular reason for that?

2017-03-15 18:40 UTC, vsreekanti commented on ground-core/src/main/java/edu/berkeley/ground/api/models/EdgeFactory.java
> +  public abstract Edge create(String name, Map<String, Tag> tags) throws GroundDBException;
There's no need for this change. `GroundDBException` is a subclass of `GroundException`. DB exceptions exist primarily for internal purposes. No need to expose them to world.

2017-03-15 18:40 UTC, vsreekanti commented on ground-core/src/main/java/edu/berkeley/ground/api/versions/cassandra/CassandraItemFactory.java
> +      if (parentId != 0 && !dag.checkItemInDag(parentId)) {
lol, good catch. No idea what I was thinking when I wrote that...

2017-03-15 18:40 UTC, vsreekanti commented on ground-core/src/main/java/edu/berkeley/ground/db/CassandraClient.java
> +        insertValues.stream().map(DbDataContainer::getField).collect(Collectors.joining(", "));
Do we know if there's overhead associated with converting `List`s to `Stream`s? I'm assuming they've optimized things enough for there not to be, but it'd be good to know for sure.

2017-03-15 20:18 UTC, mc10 commented on ground-core/src/main/java/edu/berkeley/ground/api/models/EdgeFactory.java
> +  public abstract Edge create(String name, Map<String, Tag> tags) throws GroundDBException;
Hmm fair enough, I was just trying to unify the use of the DB exceptions, as they were GroundException in one spot and GroundDBException in another spot (sometimes in the same file).

2017-03-15 20:22 UTC, kevinji commented on ground-core/src/main/java/edu/berkeley/ground/db/CassandraClient.java
> +        insertValues.stream().map(DbDataContainer::getField).collect(Collectors.joining(", "));
There's probably some degree of overhead, but I don't think it should be significant. (Also, the code for this section hasn't changed from my previous PR; GitHub just doesn't show super great diffs.)

2017-03-16 02:27 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-03-16 02:27 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ground-PRB/15/
Test FAILed.

2017-03-16 02:29 UTC, vsreekanti commented
Ignore this failure, sorry. In the middle of reconfiguring the PRB.

2017-03-16 02:31 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-03-16 02:31 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ground-PRB/16/
Test FAILed.

2017-03-16 02:51 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2017-03-16 02:51 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ground-PRB/17/
Test FAILed.

2017-03-20 19:08 UTC, vsreekanti approved these changes

2017-03-20 19:08 UTC, merged